import {
  Banknote,
  BanknoteArrowDown,
  Car,
  CircleEllipsis,
  Cross,
  Droplet,
  HandCoins,
  HousePlus,
  Lightbulb,
  ScanBarcode,
  ShoppingBag,
  ShoppingCart,
  Utensils,
  Wifi,
} from "lucide-react";
export const categoryList = [
  {
    id: 1,
    icon: <Banknote />,
    categoria: "Salário",
    color: "#41CE1B",
  },
  {
    id: 2,
    icon: <BanknoteArrowDown />,
    categoria: "Depósito",
    color: "#2BB46B",
  },
  {
    id: 3,
    icon: <ScanBarcode />,
    categoria: "Contas",
    color: "#D98B1C",
  },
  {
    id: 4,
    icon: <HousePlus />,
    categoria: "Aluguel",
    color: "#D63737",
  },
  {
    id: 5,
    icon: <HandCoins />,
    categoria: "Empréstimo",
    color: "#863CBA",
  },
  {
    id: 6,
    icon: <Lightbulb />,
    categoria: "Luz",
    color: "#E7E955",
  },
  {
    id: 7,
    icon: <Droplet />,
    categoria: "Água",
    color: "#79C7E5",
  },
  {
    id: 8,
    icon: <Wifi />,
    categoria: "Internet",
    color: "#6A7DE3",
  },
  {
    id: 9,
    icon: <ShoppingCart />,
    categoria: "Supermercado",
    color: "#56E49D",
  },
  {
    id: 10,
    icon: <Car />,
    categoria: "Transporte",
    color: "#D66A7C",
  },
  {
    id: 11,
    icon: <ShoppingBag />,
    categoria: "Shopping",
    color: "#93AAE5",
  },
  {
    id: 12,
    icon: <Utensils />,
    categoria: "Restaurante",
    color: "#E796E2",
  },
  {
    id: 13,
    icon: <Cross />,
    categoria: "Saúde",
    color: "#FF6D6D",
  },
  {
    id: 14,
    icon: <CircleEllipsis />,
    categoria: "Outros",
    color: "#E9F5FF",
  },
];
